# Generated by Django 3.2.13 on 2022-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocDate', models.DateField(blank=True, null=True)),
                ('DocNo', models.CharField(max_length=150, null=True)),
                ('Customer', models.CharField(max_length=150, null=True)),
                ('ProductCode', models.CharField(max_length=150, null=True)),
                ('ProductName', models.CharField(max_length=250, null=True)),
                ('SalesUnit', models.CharField(max_length=150, null=True)),
                ('SalesQty', models.IntegerField()),
            ],
        ),
    ]
